# Site settings
title: Rory Little
description: Rory Little's website and blog
url: "oneorten.dev"

permalink: /blog/:title/

# User settings
user:
  name: Rory Little
  title: Software Engineer
  email: rorylit@gmail.com

social:
  twitter: _rorylittle
  github: oneorten
  linkedin: rorylittle

sass:
  sass_dir: _sass

markdown: kramdown
mathjax: true

