# Site settings
title: Rory Little
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "oneinten.dev" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rory Little
user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff. Visit my blog here <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: Software Engineer
email: rorylit@gmail.com
social:
  twitter: _rorylittle
  github: idlys
  linkedin: rorylittle

sass:
  sass_dir: _sass

